intents:
  - general_faq
  - greet
  - goodbye

entities:
  - designation
  - country

slots:
  designation:
    type: text
  country:
    type: text

templates:
  utter_greet:
    - 'Hello, how can I help you?'
    - 'Hi, I am here to help.'
  utter_goodbye:
    - 'Bye :('
  utter_ask_country:
    - 'What country?'

actions:
  - utter_greet
  - utter_ask_country
  - utter_goodbye